# $Id: Makefile 5427 2009-03-02 21:40:57Z yanovich $

include Makefile.path

PROG=		slimmns_format
SRCS=		slimmns_format.c
SRCS+=          ${PFL_BASE}/psc_util/alloc.c
SRCS+=          ${PFL_BASE}/psc_util/log.c

include ${SLASHMK}
