# Permalinks
#
permalink:	pretty

# Setup
title:		SLASH2
tagline:	'blog'
description:	'Posts'
url:		http://slash2.psc.edu/
baseurl:	'https://pscedu.github.io/slash2/'
paginate:	5
encoding:	UTF-8

# About/contact
author:
  name:		Pittsburgh Supercomputing Center
  url:		http://www.psc.edu/
  email:	remarks@psc.edu

# Custom vars
version:	1.0.0
