.\" $Id$
.\" %PSC_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2008-2010, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd February 17, 2011
.Dt SLASHD 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm slashd
.Nd
.Tn SLASH
metadata server daemon
.Sh SYNOPSIS
.Nm slashd
.Op Fl D Ar datadir
.Op Fl f Ar conf
.Op Fl p Ar zfspoolcache
.Op Fl S Ar socket
.Ar zfspoolname
.Sh DESCRIPTION
The
.Nm
daemon serves metadata requests to
.Tn SLASH
file system clients and
.Tn I/O
nodes.
.Pp
.Ar zfspoolname
specifies the name of the
.Tn ZFS
pool to import for use as the backing metadata file system.
The options are as follows:
.Bl -tag -width Ds
.It Fl D Ar datadir
Specify an alternative directory where operation data is stored.
Defaults to
.Pa /var/lib/slash .
.It Fl f Ar conf
Specify an alternative configuration file.
Defaults to
.Pa /etc/slash.conf .
See
.Xr slash.conf 5
for more details.
.It Fl p Ar zfspoolcache
Specify the path to the
.Tn ZFS
file system pool cache file.
This speeds up the
.Tn ZFS
pool discovery process.
.It Fl S Ar socket
Specify an alternative path for the named socket through which
.Nm
operation can be controlled via
.Xr slmctl 8 .
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Ic %h
the machine hostname
.It Ic %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/slash. Ns Ic %h Ns Pa .sock .
.El
.Sh ENVIRONMENT
.Bl -tag -width LNET_NETWORKSx
.It Ev LNET_NETWORKS
Override the default Lustre networks determined from
.Pa slash.conf
and the machine's networking configuration.
See
.Xr pflenv 7
for more details.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/slash.conf
default
.Tn SLASH
network configuration
.It Pa /var/lib/slash/authbuf.key
inter-daemon communication key
.It Pa /var/lib/slash/ion_bmaps.odt
map of
.Tn I/O
node file block ownership
.It Pa /var/lib/slash/op-journal
pending metafile operations journal
.It Pa /var/lib/slash/op-namespace
pending namespace operations journal
.It Xo
.Pa /var/run/slashd. Ns Ic %h Ns Pa .sock
.Xc
default
.Nm
control socket
.El
.Sh SEE ALSO
.Xr slash.conf 5 ,
.Xr pflenv 7 ,
.Xr sladm 7 ,
.Xr mount_slash 8 ,
.Xr slmctl 8 ,
.Xr sliod 8
