.\" $Id$
.Dd July 7, 2008
.Dt SLASHD 8
.ds volume Pittsburgh Supercomputing Center
.Os http://www.psc.edu/
.Sh NAME
.Nm slashd
.Nd slash metadata server daemon
.Sh SYNOPSIS
.Nm slashd
.Op Fl f Ar conf
.Op Fl S Ar socket
.Sh DESCRIPTION
The
.Nm
daemon serves metadata requests to slash file system clients.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar conf
Specify an alternative configuration file.
Defaults to
.Pa /etc/slash.conf .
See
.Xr slash.conf 5
for more details.
.It Fl S Ar socket
Specify an alternative named socket file for control operations
.Pq see Xr slctl 8 .
Defaults to
.Pa /var/run/slashd.sock .
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/slash.conf
default
.Nm
configuration
.It Pa /var/run/slashd.sock
default
.Nm
control socket
.El
.Sh SEE ALSO
.Xr slash.conf 5 ,
.\" .Xr lnet-env 7 ,
.Xr mount_slash 8 ,
.Xr slctl 8 ,
.Xr sliod 8
