CREATE TABLE s2ts_run (
	id		INT		NOT NULL	AUTO_INCREMENT,
	suite_name	VARCHAR(16),
	launch_date	TIMESTAMP,
	user		VARCHAR(32),
	diff		MEDIUMTEXT,
	status		INT,
	output		MEDIUMTEXT,
	sl2_commid	CHAR(40),
	pfl_commid	CHAR(40),

	PRIMARY KEY(id),
	INDEX(user)
);

CREATE TABLE s2ts_result (
	id		INT		NOT NULL	AUTO_INCREMENT,
	run_id		INT		NOT NULL,
	task_id		INT		NOT NULL,
	test_name	VARCHAR(32),
	duration_ms	LONG,

	PRIMARY KEY(id),
	INDEX(run_id),
	INDEX(test_name)
);
