.\" $Id$
.\" %GPL_START_LICENSE%
.\" ---------------------------------------------------------------------
.\" Copyright 2015, Google, Inc.
.\" Copyright (c) 2011-2013, Pittsburgh Supercomputing Center (PSC).
.\" All rights reserved.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or (at
.\" your option) any later version.
.\"
.\" This program is distributed WITHOUT ANY WARRANTY; without even the
.\" implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
.\" PURPOSE.  See the GNU General Public License contained in the file
.\" `COPYING-GPL' at the top of this distribution or at
.\" https://www.gnu.org/licenses/gpl-2.0.html for more details.
.\" ---------------------------------------------------------------------
.\" %END_LICENSE%
.Dd October 21, 2011
.Dt CURSOR_MGR 8
.ds volume PSC \- SLASH2 Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm cursor_mgr
.Nd manipulate
.Tn SLASH2
metadata cursor file
.Sh SYNOPSIS
.Nm cursor_mgr
.Op Fl dv
.Op Fl f Ar fid
.Op Fl x Ar txg
.Fl c cursorfile
.Sh DESCRIPTION
The
.Nm
utility manipulates the
.Tn SLASH2
metadata cursor file.
The cursor file tracks operations written to the
.Tn SLASH2 MDS
journal.
The file must be accessible via the system's native file system
interface, meaning the
.Tn MDS
backing file system must be directly mounted via
.Xr zfs-fuse 8 .
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl c Ar cursor_file
Cursor file to access.
.It Fl d
Display the contents of the cursor file.
No modifications are made.
.It Fl f Ar fid
Set the last allocated
.Tn FID
.Pq file identifier
.It Fl x Ar txg
Set the last transaction group used.
.It Fl v
Display the previous contents of the cursor file while modifying.
.El
.Sh EXAMPLES
Set the cursor to
.Tn FID
1 and transaction group 1:
.Pp
.D1 $ cursor_mgr -c /slmdfs/.slmd/cursor -f 1 -x 1
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8
