# $Id$

ROOTDIR=../..
include ${ROOTDIR}/Makefile.path

DOC+=	attr.xdc
DOC+=	auth.xdc
DOC+=	bmap.xdc
DOC+=	build.xdc
DOC+=	clientio.xdc
DOC+=	config.xdc
DOC+=	failure.xdc
DOC+=	garbage.xdc
DOC+=	iod.xdc
DOC+=	ios-types.xdc
DOC+=	lease.xdc
DOC+=	mds-fs-recovery.xdc
DOC+=	net.xdc
DOC+=	run.xdc
DOC+=	slccd.xdc
DOC+=	st_blocks.xdc
DOC+=	truncate.xdc
DOC+=	upsch.xdc

include ${SLASHMK}
