# $Id$

ROOTDIR=../..
include ${ROOTDIR}/Makefile.path

DOC+= attribute-handling.txt
DOC+= auth.txt
DOC+= bmap.xdc
DOC+= clientio.xdc
DOC+= config-example.xdc
DOC+= config.xdc
DOC+= crc.xdc
DOC+= failure.xdc
DOC+= garbage-collection.txt
DOC+= iod.xdc
DOC+= lease.xdc
DOC+= lustre-networks.txt
DOC+= mds-bmap-mgt.xdc
DOC+= run.xdc
DOC+= slccd.txt
DOC+= stat_blocks.txt
DOC+= truncate.txt
DOC+= upsch.txt

include ${SLASHMK}
