.\" $Id$
.Dd February 25, 2009
.Dt MSCTL 8
.ds volume PSC \- Slash Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm msctl
.Nd slash file system mount daemon runtime control
.Sh SYNOPSIS
.Nm msctl
.Op Fl HIR
.Op Fl c Ar cmd
.Op Fl h Ar table
.Op Fl i Ar iostatspec
.Op Fl L Ar listspec
.Op Fl m Ar meterspec
.Op Fl P Ar poolspec
.Op Fl p Ar paramspec
.Op Fl Q Ar replrqspec
.Op Fl r Ar replstspec
.Op Fl S Ar socket
.Op Fl s Ar showspec
.Op Fl U Ar replrqspec
.Sh DESCRIPTION
The
.Nm
utility controls
.Xr mount_slash 8
behavior.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar cmd
Instruct
.Xr mount_slash 8
to perform one of the following actions:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Ic exit
Completely terminate
.Xr mount_slash 8
execution.
.El
.It Fl H
Suppress display of headers.
.It Fl h Ar table
Query bucket usage statistics for the given hash table(s).
.Ar table
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm threads
Slash threads
.El
.Pp
The value
.Cm all
may be specified to query all hash table statistics.
.It Fl I
Do not use human-readable numbers for large numerical displays,
e.g. show
.Li 1MB
.Pq one megabyte
as
.Li 1048576.
.It Fl i Ar iostatspec
Query I/O statistics.
.Ar iostatspec
has the following format:
.Pp
.Bd -unfilled -offset indent
.Ar iostat Ns Op , Ns Ar ...
.Ed
.Pp
.Ar iostat
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It foo
.El
.Pp
The value
.Cm all
may be specified to query all I/O statistics.
.It Fl L Ar listspec
Query list cache information for the given list(s).
.Ar listspec
has the following format:
.Pp
.Bd -unfilled -offset indent
.Sm off
.Ar list
.Op , Ar ...
.Sm on
.Ed
.Pp
.Ar list
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm fidcclean
Used FID cache entries.
.It Cm fidcdirty
Dirty FID cache entries.
.It Cm fidcfree
Unused FID cache entries.
.El
.Pp
The value
.Cm all
may be specified to retrieve information about all list caches.
.It Fl m Ar meterspec
Report progress information in meters.
.Ar meterspec
has the following format:
.Bd -unfilled -offset indent
.Ar meter Ns Op , Ns Ar ...
.Ed
.Pp
.Ar meter
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm repl- Ns Ar nid
Replication of inode
.Ar fid
metadata to server
.Ar nid .
.El
.Pp
The value
.Cm all
may be specified to retrieve information about all meters.
.It Fl P Ar poolspec
Report pool parameters.
.Ar poolspec
has the following format:
.Bd -unfilled -offset indent
.Ar pool Ns Op , Ns Ar ...
.Ed
.Pp
The value
.Ic all
may be specified to retrieve information about all pools.
.It Fl p Ar paramspec
Query/manipulate operational control parameters.
.Ar paramspec
has the following format:
.Pp
.Bd -unfilled -offset indent
.Sm off
.Oo Ar thread-name Ns . Oc Ar param
.Op = Ar value
.Sm on
.Ed
.Pp
See
.Sx Thread Specification
for details on specifying
.Ar thread-name .
.Pp
.Ar param
may be one of the following:
.Bl -tag -offset ind -width Ds
.It Ic log.level Ns Op . Ns Ar subsystem
The logging level of debug message output.
Thread-specific.
.Pp
.Ar subsystem
may be one of the following:
.Pp
.Bl -column addrcacheX addrcacheX addrcacheX -offset indent
.It Cm addrcache Ta Cm chunkmap Ta Cm ciod
.It Cm fileops Ta Cm inodecache Ta Cm lnet
.It Cm other Ta Cm read Ta Cm svc
.It Cm sync
.El
.Pp
If
.Ar subsystem
is left unspecified, all subsystems will be affected.
.Pp
The logging level value may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm none
No logging
.It Cm error
Recoverable failures
.It Cm warn
Something wrong which requires attention
.It Cm notify
Something unusual which recommends attention
.It Cm info
Informational messages
.It Cm debug
Debugging messages
.It Cm trace , all
All messages
.El
.El
.Pp
Fields applicable to all threads (i.e. global parameters) may
be addressed by specifying
.Dq everyone
as the
.Ar thread-name
or by leaving
.Ar thread-name
unspecified altogether.
.Pp
.It Fl Q Ar replrqspec
Perform data replication as specified by
.Ar replrqspec .
The
.Tn I/O
node responsible for the data regions specified will propagate the data
to all other
.Tn I/O
nodes in the containing
.Tn I/O
system.
.Pp
.Ar replrqspec
has the following format:
.Bd -unfilled -offset indent
.Sm off
.Ar filename
.Op : Ar bmapno Op , Ar ...
.Sm on
.Ed
.Pp
If
.Ar bmapno
is not specified, all bmaps will be replicated; otherwise, only the
bmaps with the given indexes will be replicated.
.Pp
This option may be specified multiple times.
.It Fl R
Apply file operations such as issuing replication requests recursively.
.It Fl r Ar file
List replication status for the given
.Ar file
bmaps.
If
.Ar file
is the special name
.Sq \&: ,
all pending replications will be queried.
.Pp
This option may be specified multiple times.
.It Fl S Ar socket
Specify an alternative socket file.
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Ic %h
the machine hostname
.It Ic %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/mount_slash. Ns Ic %h Ns Pa .sock .
.It Fl s Ar showspec
Query and show
.Xr mount_slash 8
parameter values.
.Ar showspec
has the following format:
.Bd -unfilled -offset indent
.Sm off
.Ar param
.Op : Ar thread-name Op , Ar ...
.Sm on
.Ed
.Pp
See
.Sx Thread Specification
for details on specifying
.Ar thread-name .
.Pp
.Ar param
may be specified as any non-ambiguous prefix abbreviation of the
following:
.Pp
.Bl -tag -offset indent -width 12n -compact
.It Cm loglevels
Query thread logging levels.
.It Cm stats
Query thread activity statistics.
.El
.Pp
This option may be specified multiple times.
.It Fl U Ar replrqspec
Cancel ongoing file replication requests as specified by
.Ar replrqspec .
See
.Fl Q
for details of the format of
.Ar replrqspec .
.El
.Ss Thread Specification
Options which take
.Ar thread-name
parameters may be specified by one or more of the following tokens,
separated by commas:
.Pp
.Bl -tag -compact -offset indent -width 15n
.It Cm msbflushthr
Bmap flusher thread
.It Cm msctlthr
Control thread
.It Cm mseqpollthr
Lustre EQPoll thread
.It Cm msfsthr Ns Ar %d
File system service thread
.It Cm msfusethr
.Tn FUSE
master thread
.It Cm msrcmthrthr Ns Ar %02d
.Tn MDS RPC
request service
.It Cm mstintvthr
Timer interval thread
.It Cm mstiosthr
Timed
.Tn I/O
stats updater thread
.It Cm msusklndplthr Ns Ar %d
Lustre userland socket poll thread
.It Cm everyone
All threads (default, where applicable)
.El
.Sh FILES
.Bl -tag -width Pa
.It Xo
.Pa /var/run/mount_slash. Ns Ic %h Ns Pa .sock
.Xc
default
.Xr mount_slash 8
control socket
.El
.Sh SEE ALSO
.Xr mount_slash 8 ,
.Xr slashd 8
