.\" $Id$
.\" %PSC_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2008-2010, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd November 2, 2010
.Dt MOUNT_SLASH 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm mount_slash
.Nd mount a
.Tn SLASH
file system
.Sh SYNOPSIS
.Nm mount_slash
.Op Fl dU
.Op Fl D Ar datadir
.Op Fl f Ar conf
.Op Fl I Ar iosystem
.Op Fl M Ar mds
.Op Fl o Ar mountopt
.Op Fl p Ar #prefetch
.Op Fl S Ar socket
.Ar mountpoint
.Sh DESCRIPTION
The
.Nm
utility attachs a
.Tn SLASH
file system under the specified
.Ar mountpoint .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl D Ar datadir
Specify an alternative directory where operation data is stored.
Defaults to
.Pa /var/lib/slash .
.It Fl d
Enable low-level file system debug messages.
.It Fl f Ar conf
Specify an alternative configuration file.
Defaults to
.Pa /etc/slash.conf .
.It Fl I Ar iosystem
Specify the preferred
.Tn I/O
system resource name.
.It Fl M Ar mds
Specify the primary metadata server resource name.
.It Fl p Ar #prefetch
Specify the maximum number of file
.Xr stat 2
buffers to fetch when performing
.Tn READDIR RPC Ns s .
The default is as many as can fit.
.It Fl o Ar mountopt
Pass additional options to the low-level file system mounter.
.It Fl S Ar socket
Specify an alternative path for the named socket through which
.Nm
operation can be controlled via
.Xr msctl 8 .
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Ic %h
the machine hostname
.It Ic %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/mount_slash. Ns Ic %h Ns Pa .sock .
.It Fl U
Perform a
.Xr umount 8
at the location specified by
.Ar mountpoint
before attempting to bring up the file system.
.El
.Sh ENVIRONMENT
.Bl -tag -width LNET_NETWORKSx
.It Ev LNET_NETWORKS
Override the default Lustre networks determined from
.Pa slash.conf
and the machine's networking configuration.
See
.Xr pflenv 7
for more details.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/slash.conf
default
.Tn SLASH
network configuration
.It Pa /var/lib/slash/authbuf.key
inter-daemon communication key
.It Xo
.Pa /var/run/mount_slash. Ns Ic %h Ns Pa .sock
.Xc
default
.Nm
control socket
.El
.Sh SEE ALSO
.Xr slash.conf 5 ,
.Xr pflenv 7 ,
.Xr sladm 7 ,
.Xr msctl 8 ,
.Xr slashd 8 ,
.Xr sliod 8 ,
.Xr umount 8
