.\" $Id$
.Dd February 25, 2009
.Dt MOUNT_SLASH 8
.ds volume Pittsburgh Supercomputing Center
.Os http://www.psc.edu/
.Sh NAME
.Nm mount_slash
.Nd mount a slash file system
.Sh SYNOPSIS
.Nm mount_slash
.Op Fl s
.Op Fl o Ar options
.Op Fl S Ar socket
.Ar mountpoint
.Sh DESCRIPTION
The
.Nm
utility attachs a slash file system mount under the specified
.Ar mountpoint .
.Pp
The options are as follows:
.Bl -tag -width Ds -offset indent
.Pq i.e. do not fork and enter daemon operation .
.It Fl o Ar options
Enable a FUSE-specific option.
.It Fl S Ar socket
Specify an alternative path for the named socket through which
.Nm
operation can be controlled via
.Xr msctl 8 .
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Ic %h
the machine hostname
.It Ic %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/mount_slash. Ns Ar %h Ns Pa .sock .
.It Fl s
Disable multithreaded operation.
.El
.Sh ENVIRONMENT
.Bl -tag -width SLASH_MDS_SERVER_NIDx
.It Ev SLASH_MDS_SERVER_NID
Slash MDS LNET NID
.Pq connection address string .
.It Ev SLASH_IO_SERVER_NIDS
Comma-separated list of I/O server LNET NIDs.
.It Ev SLASH2_PIOS_ID
Preferred I/O server LNET NID.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/slash.conf
default
.Nm
configuration
.It Xo
.Pa /var/run/mount_slash. Ns Ar %h Ns Pa .sock
.Xc
default
.Nm
control socket
.El
.Sh SEE ALSO
.Xr pflenv 7 ,
.Xr msctl 8 ,
.Xr slashd 8 ,
.Xr sliod 8 ,
.Xr umount 8
