.\" $Id$
.Dd June 10, 2008
.Dt MOUNT_SLASH 8
.ds volume Pittsburgh Supercomputing Center
.Os http://www.psc.edu/
.Sh NAME
.Nm mount_slash
.Nd slash file system mounter
.Sh SYNOPSIS
.Nm mount_slash
.Op Ar options
.Ar mountpoint
.Sh DESCRIPTION
The
.Nm
utility attachs a slash file system mount under the specified
.Ar mountpoint .
.Sh ENVIRONMENT
.Bl -tag -width Ev
.It Ev SLASH_SERVER_NID
Slash MDS LNET NID
.Pq connection address string .
.El
.Sh SEE ALSO
.Xr msctl 8 ,
.Xr slashd 8 ,
.Xr sliod 8 ,
.Xr umount 8
.\" .Xr lnet-env-vars 7
