# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		replbit_test
SRCS+=		replbit_test.c
SRCS+=		${SLASH_BASE}/share/slerr.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/printhex.c

MODULES+=	lnet-hdrs

include ${SLASHMK}
