# $Id$

include ../Makefile.path

PROG=		replbit_test
SRCS+=		replbit_test.c
SRCS+=		${SLASH_BASE}/share/slerr.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

MODULES+=	lnet-hdrs

include ${SLASHMK}
