# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		fidviz
SRCS+=		fidviz.c
SRCS+=		${SLASH_BASE}/share/mkfn.c
SRCS+=		${SLASH_BASE}/share/slutil.c
SRCS+=		${SLASH_BASE}/sliod/fidc_iod.c
SRCS+=		${PFL_BASE}/psc_util/rlimit.c

MODULES+=	pfl lnet-hdrs

include ${SLASHMK}
