.\" $Id$
.Dd February 25, 2009
.Dt SLIOD 8
.ds volume PSC \- Slash Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm sliod
.Nd slash I/O server daemon
.Sh SYNOPSIS
.Nm sliod
.Op Fl f Ar conf
.Op Fl S Ar socket
.Sh DESCRIPTION
The
.Nm
daemon serves I/O requests to slash file system clients.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar conf
Specify an alternative configuration file.
Defaults to
.Pa /etc/slash.conf .
See
.Xr slash.conf 5
for more details.
.It Fl S Ar socket
Specify an alternative path for the named socket through which
.Nm
operation can be controlled via
.Xr slioctl 8 .
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Ic %h
the machine hostname
.It Ic %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/sliod. Ns Ic %h Ns Pa .sock .
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/slash.conf
default
.Nm
configuration
.It Xo
.Pa /var/run/sliod. Ns Ic %h Ns Pa .sock
.Xc
default
.Nm
control socket
.El
.Sh SEE ALSO
.Xr slash.conf 5 ,
.Xr pflenv 7 ,
.Xr mount_slash 8 ,
.Xr slashd 8 ,
.Xr slioctl 8
