.\" $Id$
.\" %PSC_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2008-2010, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd August 12, 2010
.Dt SLIOD 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm sliod
.Nd
.Tn SLASH I/O
server daemon
.Sh SYNOPSIS
.Nm sliod
.Op Fl D Ar datadir
.Op Fl f Ar conf
.Op Fl S Ar socket
.Ar mds-resource
.Sh DESCRIPTION
The
.Nm
daemon serves
.Tn I/O
requests to
.Tn SLASH
file system clients.
.Pp
The
.Ar mds-resource
parameter specifies the
.Xr slash.conf 5
resource name of the primary metadata server to use for communicating
file metadata.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl D Ar datadir
Specify an alternative directory where operation data is stored.
Defaults to
.Pa /var/lib/slash .
.
.It Fl f Ar conf
Specify an alternative configuration file.
Defaults to
.Pa /etc/slash.conf .
See
.Xr slash.conf 5
for more details.
.It Fl S Ar socket
Specify an alternative path for the named socket through which
.Nm
operation can be controlled via
.Xr slictl 8 .
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Ic %h
the machine hostname
.It Ic %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/sliod. Ns Ic %h Ns Pa .sock .
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/slash.conf
default
.Tn SLASH
network configuration
.It Pa /var/lib/slash/authbuf.key
inter-daemon communication key
.It Xo
.Pa /var/run/sliod. Ns Ic %h Ns Pa .sock
.Xc
default
.Nm
control socket
.El
.Sh SEE ALSO
.Xr slash.conf 5 ,
.Xr pflenv 7 ,
.Xr sladm 7 ,
.Xr mount_slash 8 ,
.Xr slashd 8 ,
.Xr slictl 8
