.\" $Id$
.\" %GPL_START_LICENSE%
.\" ---------------------------------------------------------------------
.\" Copyright 2015-2016, Google, Inc.
.\" Copyright (c) 2008-2015, Pittsburgh Supercomputing Center (PSC).
.\" All rights reserved.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or (at
.\" your option) any later version.
.\"
.\" This program is distributed WITHOUT ANY WARRANTY; without even the
.\" implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
.\" PURPOSE.  See the GNU General Public License contained in the file
.\" `COPYING-GPL' at the top of this distribution or at
.\" https://www.gnu.org/licenses/gpl-2.0.html for more details.
.\" ---------------------------------------------------------------------
.\" %END_LICENSE%
.\" %PFL_MODULES lnet pflenv %
.Dd April 19, 2016
.Dt SLIOD 8
.ds volume PSC \- SLASH2 Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm sliod
.Nd
.Tn SLASH2 I/O
server daemon
.Sh SYNOPSIS
.Nm sliod
.Op Fl V
.Op Fl D Ar datadir
.Op Fl f Ar conf
.Op Fl S Ar socket
.Op Ar mds-resource
.Sh DESCRIPTION
The
.Nm
daemon serves
.Tn I/O
requests to
.Tn SLASH2
file system clients.
.Pp
The
.Ar mds-resource
parameter specifies the
.Xr slcfg 5
resource name of the primary metadata server to use for communicating
file metadata.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl D Ar datadir
Specify an alternative directory where operation data is stored.
Defaults to
.Pa /var/lib/slash .
.
.It Fl f Ar conf
Specify an alternative configuration file.
Defaults to
.Pa /etc/slash/slcfg .
See
.Xr slcfg 5
for more details.
.It Fl S Ar socket
Specify an alternative path for the named socket through which
.Nm
operation can be controlled via
.Xr slictl 8 .
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Ic %h
the machine hostname
.It Ic %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/sliod. Ns Ic %h Ns Pa .sock .
.It Fl V
Print version and exit.
.El
.\" %PFL_INCLUDE $PFL_BASE/doc/env.mdoc {
.\"	portpid => 1,
.\"	lnets_note => <<'EOF',
.\"		.Pp
.\"		This is determined by default automatically from
.\"		.Xr slcfg 5
.\"		and the machine's networking configuration but can be
.\"		overridden if set specifically in
.\"		.Xr slcfg 5
.\"		or in the environment.
.\"		EOF
.\"	subsys => {
.\"		bmap	=> "Block map structures",
.\"		fcmh	=> ".Tn FID\ncache members",
.\"		slvr	=> "Sliver\n.Pq Tn I/O No slab\nhandling",
.\"	},
.\"	env => {
.\"		CONFIG_FILE =>		"Path to configuration file\n.Pq see Fl f .",
.\"		CTL_SOCK_FILE =>	"Path to control socket file\n.Pq see Fl S .",
.\"	},
.Sh ENVIRONMENT
.Bl -tag -width 3n
.It Ev CONFIG_FILE
Path to configuration file
.Pq see Fl f .
.It Ev CTL_SOCK_FILE
Path to control socket file
.Pq see Fl S .
.It Ev LNET_ACCEPT
Specify constraints on which connections are accepted.
May be
.Ic secure
for allowing connections only from
.Tn TCP
port 1023 and lower
.I all
to allow all, or
.Ic none
to disallow connections from user processes.
Defaults to
.Ic all .
.It Ev LNET_ACCEPT_BACKLOG
Specify the
.Xr listen 2
queue depth.
Defaults to 127.
.It Ev LNET_ACCEPT_PORT
Specify an alternate local
.Xr tcp 7
port for listening network sockets created by the Lustre networking
stack.
Defaults to 988.
.It Ev LNET_ACCEPT_TIMEOUT
Specify the number of seconds to wait for activity after a socket is
accepted.
Defaults to 5 seconds.
.It Ev LNET_IP2NETS
The list of
.Xr ip 4
networks and corresponding Lustre network names.
.It Ev LNET_NETWORKS
The list of networks and interfaces known to the Lustre networking
stack.
.Pp
This is determined by default automatically from
.Xr slcfg 5
and the machine's networking configuration but can be
overridden if set specifically in
.Xr slcfg 5
or in the environment.
.Pp
Examples:
.Bd -literal -offset 3n
tcp1(eth0),tcp1(eth1)
sdp4(ib0)
.Ed
.It Ev LNET_ROUTES
The list of Lustre routes for interconnecting networks.
.Pp
Examples:
.Bd -literal -offset 3n
tcp1 3@ptl1
tcp1 [2560,2563,2568,2571,2572,2575]@ptl0
.Ed
.It Ev PFL_SYSLOG_IDENT
Set to a custom value to pass as the
.Ar ident
parameter to
.Xr openlog 3
.Po used when
.Ev PFL_SYSLOG
is enabled
.Pc .
The following tokens are replaced in the value specified:
.Pp
.Bl -tag -offset 3n -width 6n -compact
.It Cm %n
the program (binary) name
.El
.It Ev PFL_SYSLOG_PIPE
Set to non-zero to launch a process that forwards all log messages
to the given shell pipeline, usually
.Dq logger .
.It Ev PSC_DUMPSTACK Pq debugging
When segmentation violations or fatal error conditions occur, try to
print a stack trace if this variable is defined.
.It Ev PSC_LOG_FILE
This path specifies the file name where log messages are written.
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset 3n -width 6n -compact
.It Cm %t
the number of seconds since the Epoch
.It Cm %%
a literal
.Sq %
character
.El
.It Ev PSC_LOG_FORMAT
This
.Xr printf 3 Ns -like
value is prepended to each log message reported.
The following specifiers are recognized
.Pq not all may be applicable :
.Pp
.Bl -tag -offset 3n -compact -width 6n
.It Ic A
RPC peer address
.It Ic B
source code file base name
.It Ic D Ns Aq Ar fmt
.Xr strftime 3 Ns -like
format of time
.It Ic F
source code function name
.It Ic f
source code file full path name
.It Ic H
full system host name
.It Ic h
short system host name
.It Ic I
.Xr pthread 3
.Tn ID
of thread which generated log message
.It Ic i
system
.Tn ID
of daemon thread which generated log message
.It Ic L
numeric level of log message importance
.It Ic l
source code file line number
.It Ic P
file system request's originating process'
.Tn PID
.It Ic N
daemon executable file base name
.It Ic n
symbolic thread name which generated log message
.It Ic r
.Tn MPI
rank of process
.It Ic S
function call stack with frames separated by
.Sq :\&
.It Ic s
seconds since Epoch
.Pq same as Li %D\*(Lt%s\*(Gt
.It Ic t
subsystem
.Tn ID
which generated log message
.It Ic T
subsystem name which generated log message
.It Ic U
file system request's originating process' user
.Tn ID
.It Ic u
microseconds into current second when generated
.It Ic X
file system request's originating process'
executable name
.El
.Pp
Examples:
.Bd -literal -offset 3n
[%D<%s>:%06u %n %F %l]
.Ed
.It Ev PSC_LOG_LEVEL
Each log message has an associated
.Dq level
numeric value which can be used to filter granularity of importance.
This environment variable specifies the minimum level of importance
necessary for messages to be reported.
.Pp
The following values are recognized:
.Pp
.Bl -tag -compact -offset 3n -width 13n
.It Cm 0 , none
No logging
.It Cm 1 , error
Recoverable failures
.It Cm 2 , warn
Something wrong which requires attention
.Pq default
.It Cm 3 , notice
Something unusual which recommends attention
.It Cm 4 , info
Informational messages
.It Cm 5 , diag
Diagnostics
.It Cm 6 , debug
Debugging messages
.It Cm 7 , vdebug
Verbose debugging messages
.It Cm 8 , trace , all
Full trace messages
.El
.It Ev PSC_LOG_LEVEL_ Ns Ar subsys
Like
.Ev PSC_LOG_LEVEL ,
but applies only to the given
.Ar subsys .
.Pp
.Ar subsys
may be one of the following:
.Pp
.Bl -tag -compact -offset 3n -width 13n
.It Cm bmap
Block map structures
.It Cm def
Default
.It Cm fcmh
.Tn FID
cache members
.It Cm mem
Memory allocations and releases
.It Cm slvr
Sliver
.Pq Tn I/O No slab
handling
.El
.Pp
Examples:
.Bd -literal -offset 3n
PSC_LOG_LEVEL_mem=debug
.Ed
.It Ev PSC_MAX_NMEMMAPS
On Linux, specify the number of memory maps the process address space is
allowed to be divided into via
.Pa /proc/sys/vm/max_map_count .
Defaults to one million.
.It Ev PSC_SYSLOG
Set to non-zero to send all log messages to
.Xr syslog 3
.It Ev PSC_SYSLOG_ Ns Ar subsys
Set to non-zero to send log messages from the given
.Ar subsys
to
.Xr syslog 3
in addition to
.Em stderr .
.It Ev USOCK_CPORT
Specify an alternate remote/peer
.Xr tcp 7
port for connecting networking sockets.
Defaults to 988.
.It Ev USOCK_FAIR_LIMIT
Specify the number of packets that can be received or transmitted
without calling
.Xr poll 2 .
Defaults to one.
.It Ev USOCK_MIN_BULK
Specify the smallest bulk size permissible.
Defaults to 1024.
.It Ev USOCK_NPOLLTHREADS
Specify the number of threads to spawn to check and perform activity from
sockets.
Defaults to the minimum of the number of cores available on the system
or one quarter of the number of file descriptors available to the
process.
.It Ev USOCK_PEERTXCREDITS
Specify the number of concurrent sends to any single peer.
Defaults to 8.
.It Ev USOCK_POLL_TIMEOUT
Specify the number of seconds to wait for activity on a socket before
temporarily tending to other duties and trying again.
Defaults to one.
.It Ev USOCK_PORTPID
Specify whether to fabricate Lustre
.Tn PID
values from a connecting peer's originating
.Tn TCP
port instead of from the value specified by the peer during connect.
Defaults to on.
.It Ev USOCK_SOCKBUFSIZ
Specify an alternative value for the amount of data that can either be
queued awaiting tranmission or accumulate in a socket by the kernel
awaiting reception by a process.
Defaults to whatever value is initialized by the operating system.
.It Ev USOCK_SOCKNAGLE
Specify whether to enable the Nagle algorithm on sockets.
Defaults to disabling the Nagle algorithm.
.It Ev USOCK_TIMEOUT
Specify the number of seconds before no response on a socket triggers a
drop by the networking stack.
Defaults to 50 seconds.
.It Ev USOCK_TXCREDITS
Specify the total number of concurrent sends accumulated across all
peers.
Defaults to 256.
.El
.\" }%
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/slash/slcfg
default
.Tn SLASH2
network configuration
.It Pa /var/lib/slash/authbuf.key
inter-daemon communication key
.It Xo
.Pa /var/run/sliod. Ns Ic %h Ns Pa .sock
.Xc
default
.Nm
control socket
.El
.Sh SEE ALSO
.Xr slcfg 5 ,
.Xr sladm 7 ,
.Xr slash2client.so 5 ,
.Xr slashd 8 ,
.Xr slictl 8
