.\" $Id$
.Dd November 13, 2009
.Dt SLMKJRNL 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm slmkjrnl
.Nd create
.Tn SLASH
metadata server journal
.Sh SYNOPSIS
.Nm slmkjrnl
.Op Fl d
.Sh DESCRIPTION
The
.Nm
utility creates and formats the pending operations journal for
.Tn SLASH
metadata servers.
.Pp
The following options are available:
.Bl -tag -indent Ds
.It Fl d
Only dump the current journal data; do not format.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /var/lib/slashd/slopjrnl
pending operations journal
.El
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8
