.\" $Id$
.Dd July 2, 2010
.Dt SLMKJRNL 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm slmkjrnl
.Nd create
.Tn SLASH
metadata server operations journal
.Sh SYNOPSIS
.Nm slmkjrnl
.Op Fl fqv
.Op Fl D Ar datadir
.Sh DESCRIPTION
The
.Nm
utility creates and formats the pending operations journal for
.Tn SLASH
metadata servers.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl b Ar block-device
Specify a raw device as the journal target instead of a regular file.
This option is incompatible with
.Fl D .
.It Fl D Ar datadir
Specify an alternative directory where operation data is stored.
Defaults to
.Pa /var/lib/slashd .
.It Fl f
Format the operations journal.
.It Fl n Ar nentries
Specify the number of journal entries.
Defaults to 131072.
.It Fl q
Query and display current journal information.
No formatting is performed.
.It Fl v
Display verbose information about activity performed.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /var/lib/slashd/op-journal
pending operations journal
.El
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8
