.\" $Id$
.Dd February 15, 2008
.Dt NEWFS_SLIO 8
.ds volume Pittsburgh Supercomputing Center
.Os http://www.psc.edu/
.Sh NAME
.Nm newfs_slio
.Nd Slash sliod file system creator
.Sh SYNOPSIS
.Nm newfs_slio
.Op Fl f Ar cfgfn
.Sh DESCRIPTION
The
.Nm
utility creates and initializes file systems for use with
.Xr sliod 8 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar cfgfn
Specify the path to the configuration file.
By default,
.Pa /etc/slash.conf
is used.
.El
.Sh FILES
.Bl -tag -width Pa
.It Pa /etc/slash.conf
default Slash configuration file
.El
.Sh SEE ALSO
.Xr slash.conf 5 ,
.Xr newfs_slmd 8 ,
.Xr sliod 8
