.\" $Id$
.\" %PSCGPL_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2011-2012, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd February 28, 2012
.Dt RECLAIM 8
.ds volume PSC \- SLASH2 Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm reclaim
.Nd display or manipulate a
.Tn SLASH2
metadata reclaim log or progress log
.Sh SYNOPSIS
.Nm reclaim
.Op Fl b Ar batchno
.Op Fl i Ar id
.Op Fl p Ar reclaim-prog-log
.Op Fl r Ar reclaim-log
.Sh DESCRIPTION
The
.Nm
utility can be used for two purposes regarding SLASH2 metadata log files:
.Pp
.Bl -enum -compact -offset 3n
.It
display the contents of a reclaim log file
.It
modify a reclaim progress log file
.El
.Pp
The log file must be accessible via the system's native file system interface, meaning the
.Tn MDS
backing file system must be directly mounted via
.Xr zfs-fuse 8 .
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl b Ar batchno
The value the batch number will be updated to in the reclaim progress log file.
Default is 0.
.It Fl i Ar id
The ID of the IOS whose progress entry in the progress log file will be updated.
.It Fl p Ar reclaim-prog-log
Reclaim progress log file to dump and optionally update if
.Fl i
is also specified.
.It Fl r Ar reclaim-log
Reclaim log file to dump.
.Sh EXAMPLES
Dump the contents of a reclaim log file:
.Pp
.D1 $ reclaim -r /slmdfs/slmd/op-reclaim.43
.Pp
Dump the contents of the reclaim progress log file:
.Pp
.D1 $ reclaim -p /slmdfs/slmd/op-reclaim-prog
.Pp
Dump the contents of the reclaim progress log file and update the batchno
of the IOS with ID 802345:
.Pp
.D1 $ reclaim -p /slmdfs/slmd/op-reclaim-prog -i 802345 -b 3478
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8
