.\" $Id$
.\" %GPL_START_LICENSE%
.\" ---------------------------------------------------------------------
.\" Copyright 2015-2016, Google, Inc.
.\" Copyright (c) 2011-2014, Pittsburgh Supercomputing Center (PSC).
.\" All rights reserved.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or (at
.\" your option) any later version.
.\"
.\" This program is distributed WITHOUT ANY WARRANTY; without even the
.\" implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
.\" PURPOSE.  See the GNU General Public License contained in the file
.\" `COPYING-GPL' at the top of this distribution or at
.\" https://www.gnu.org/licenses/gpl-2.0.html for more details.
.\" ---------------------------------------------------------------------
.\" %END_LICENSE%
.Dd March 8, 2016
.Dt RECLAIM 8
.ds volume PSC \- SLASH2 Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm reclaim
.Nd display or manipulate a
.Tn SLASH2
metadata reclaim log or reclaim progress log
.Sh SYNOPSIS
.Nm reclaim
.Op Fl D
.Op Fl b Ar batchno
.Op Fl i Ar id
.Op Fl p Ar reclaim-prog-log
.Op Fl r Ar reclaim-log
.Sh DESCRIPTION
The
.Nm
utility can be used for two purposes regarding SLASH2 metadata log
files:
.Pp
.Bl -enum -compact -offset 3n
.It
display the contents of a reclaim log file
.It
display and optionally modify a reclaim progress log file
.El
.Pp
The log file must be accessible via the system's native file system
interface, meaning the MDS backing file system must be directly mounted
via
.Xr zfs-fuse 8 .
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl b Ar batchno
Update the batch number to
.Ar batchno
for the given IOS
.Pq see Fl i
in the specified reclaim progress log file
.Pq see Fl p .
.It Fl i Ar id
Specify the ID of the IOS to update from the specified reclaim progress
log file.
.It Fl D
Delete the progress entry whose ID is specified by
.Fl i
above.
Note: if the system configuration file still has the IOS listed, an
entry will be re-created for it when
.Xr slashd 8
is started as if a new IOS has been added from the perspective of
garbage reclamation.
.It Fl p Ar reclaim-prog-log
Display the contents of the given file
.Ar reclaim-prog-log .
With the
.Fl i
option, also update the file as specified.
.It Fl r Ar reclaim-log
Reclaim log file to dump.
.Sh EXAMPLES
Dump the contents of a reclaim log file:
.Pp
.D1 $ reclaim -r /slmdfs/.slmd/op-reclaim.43
.Pp
Dump the contents of a reclaim progress log file:
.Pp
.D1 $ reclaim -p /slmdfs/.slmd/op-reclaim-prog
.Pp
Dump the contents of a reclaim progress log file and update the
batchno of the IOS with ID 802345:
.Pp
.D1 $ reclaim -p /slmdfs/.slmd/op-reclaim-prog -i 802345 -b 3478
.Pp
Remove the entry for the IOS whose ID is 19071001:
.Pp
.D1 $ reclaim -D -i 19071001 -p /slmdfs/.slmd/op-reclaim-prog
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8
