.\" $Id$
.\" %PSC_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2008-2010, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd October 22, 2010
.Dt SLMCTL 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm slmctl
.Nd
.Tn SLASH MDS
daemon runtime control
.Sh SYNOPSIS
.Nm slmctl
.Op Fl HI
.Op Fl c Ar cmd
.Op Fl h Ar table
.Op Fl i Ar iostatspec
.Op Fl L Ar listspec
.Op Fl m Ar meterspec
.Op Fl P Ar poolspec
.Op Fl p Ar paramspec
.Op Fl S Ar socket
.Op Fl s Ar showspec
.Sh DESCRIPTION
The
.Nm
utility examines and manipulates
.Xr slashd 8
behavior.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar cmd
Instruct
.Xr slashd 8
to perform one of the following actions:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm exit
Completely terminate
.Xr slashd 8
execution.
.El
.It Fl H
Suppress display of headers.
.It Fl h Ar table
Query bucket usage statistics for the given hash table(s).
.Ar table
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm fidc
files
.Po file
.Tn ID
cache
.Pc
.It Cm resnid
network resources
.Pq network Tn ID
.El
.Pp
The value
.Cm all
may be specified to query all hash table statistics.
.It Fl I
Do not use human-readable numbers for large numerical displays,
e.g. show
.Li 1MB
.Pq one megabyte
as
.Li 1048576.
.It Fl i Ar iostatspec
Query I/O statistics.
.Ar iostatspec
has the following format:
.Pp
.Bd -unfilled -offset indent
.Ar iostat Ns Op , Ns Ar ...
.Ed
.Pp
.Ar iostat
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width Ds
.It Cm lni-rcv- Ns Ar if ,
.It Cm lni-snd- Ns Ar if
Data sent/received per
.Tn LNET
networking interface.
.Pp
.It Cm lusklnd- Ns Ar mode Ns Cm -rcv ,
.It Cm lusklnd- Ns Ar mode Ns Cm -snd
Data sent/received over userland socket networking device.
.Ar mode
may be
.Cm pasv
.Pq passive
or
.Cm aggr
.Pq aggregate .
.Pp
.It Cm jrnlwr- Ns Ar fn ,
.It Cm jrnlrd- Ns Ar fn
Data read/written to journal disk file
.Ar fn .
.El
.Pp
The value
.Cm all
may be specified to query all I/O statistics.
.It Fl L Ar listspec
Query list cache information for the given list(s).
.Ar listspec
has the following format:
.Pp
.Bd -unfilled -offset indent
.Sm off
.Ar list
.Op , Ar ...
.Sm on
.Ed
.Pp
.Ar list
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm fcmhidle
Clean
.Pq reapable
files
.It Cm fcmhbusy
File with pending action e.g.\&
.Tn I/O
.It Cm inflightbml
Active
.Pq inflight
bmap lease mode updates
.It Cm pendingbml
Pending bmap lease mode updates
.It Cm replstwkq
Replication status work buffers
.El
.Pp
The value
.Cm all
may be specified to retrieve information about all list caches.
.It Fl m Ar meterspec
Report progress information in meters.
.Ar meterspec
has the following format:
.Bd -unfilled -offset indent
.Ar meter Ns Op , Ns Ar ...
.Ed
.Pp
.Ar meter
may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm repl- Ns Ar nid
Replication of inode
.Ar fid
metadata to server
.Ar nid .
.El
.Pp
The value
.Cm all
may be specified to retrieve information about all meters.
.It Fl P Ar poolspec
Report pool parameters.
.Ar poolspec
has the following format:
.Bd -unfilled -offset indent
.Ar pool Ns Op , Ns Ar ...
.Ed
.Pp
The value
.Cm all
may be specified to retrieve information about all pools.
.It Fl p Ar paramspec
Query/manipulate operational control parameters.
.Ar paramspec
has the following format:
.Pp
.Bd -unfilled -offset indent
.Sm off
.Oo Ar thread-name Ns . Oc Ar param
.Op = Ar value
.Sm on
.Ed
.Pp
See
.Sx Thread Specification
for details on specifying
.Ar thread-name .
.Pp
.Ar param
may be one of the following:
.Bl -tag -offset ind -width Ds
.It Cm log.level Ns Op . Ns Ar subsystem
The logging level of debug message output.
.Pp
.Ar subsystem
may be one of the following:
.Pp
.Bl -tag -offset indent -width 12n -compact
.It Cm bmap
Block map structures
.It Cm gen
General/catch all
.It Cm jrnl
Journaling operations
.It Cm lnet
Lustre networking stack
.It Cm mem
Memory allocations and releases
.It Cm rpc
Network remote procedure calls
.El
.Pp
If
.Ar subsystem
is left unspecified, all subsystems will be affected.
.Pp
The logging level value may be one of the following:
.Pp
.Bl -tag -compact -offset indent -width 12n
.It Cm none
No logging
.It Cm error
Recoverable failures
.It Cm warn
Something wrong which requires attention
.It Cm notify
Something unusual which recommends attention
.It Cm info
Informational messages
.It Cm debug
Debugging messages
.It Cm trace , all
All messages
.El
.It Cm pool. Ns Ar name
Access the memory pool specified by
.Ar name .
The following sub-fields are available:
.Pp
.Bl -tag -compact -offset 2n -width 5n
.It Cm min
Lower bound for number of entries to which pool can shrink.
.It Cm max
Upper bound for number of entries to which pool can grow.
.It Cm size
Current number of entries contained in pool.
.El
.El
.Pp
Fields applicable to all threads (i.e. global parameters) may
be addressed by specifying
.Dq everyone
as the
.Ar thread-name
or by leaving
.Ar thread-name
unspecified altogether.
.Pp
.It Fl S Ar socket
Specify an alternative socket file.
The following tokens are replaced in the file name specified:
.Pp
.Bl -tag -offset indent -width Ds -compact
.It Cm %h
the machine hostname
.It Cm %%
a literal
.Sq %
character
.El
.Pp
The default is
.Pa /var/run/slashd. Ns Ic %h Ns Pa .sock .
.It Fl s Ar showspec
Query and show
.Xr slashd 8
parameter values.
.Ar showspec
has the following format:
.Bd -unfilled -offset indent
.Sm off
.Ar param
.Op : Ar thread-name Op , Ar ...
.Sm on
.Ed
.Pp
.Ar param
may be specified as any non-ambiguous prefix abbreviation of the
following:
.Pp
.Bl -tag -offset indent -width 12n -compact
.It Cm connections
Status of
.Tn SLASH
peers on network.
.It Cm fcmhs
.Tn FID
.Pq file- Ns Tn ID
cache members.
.It Cm loglevels
Thread logging levels.
.It Cm odtables
Disk-backed data files.
.It Cm rpcsvcs
.Tn RPC
services.
.It Cm threads
Thread activity statistics.
.El
.Pp
The special value
.Sq \&?
may be specified to display a list of recognized values.
.Pp
See
.Sx Thread Specification
for details on specifying
.Ar thread-name .
.Pp
This option may be specified multiple times.
.El
.Ss Thread Specification
Options which take
.Ar thread-name
parameters may be specified by one or more of the following tokens,
separated by commas:
.Pp
.Bl -tag -compact -offset indent -width 16n
.It Cm slmbmaptimeothr
Bmap lease timeout monitor
.It Cm slmcohthr
Bmap data coherency thread
.It Cm slmctlacthr
.Xr slashd 8
connection acceptor
.It Cm slmctlthr
.Xr slashd 8
connection processor
.It Cm slmjcursorthr
Journal cursor updater thread
.It Cm slmjthr
Master journal thread
.It Cm slmlnacthr- Ns Ar %s
.Tn LNET
network acceptor thread
.It Cm slmrcmthr
Client
.Tn RPC
request initiator thread
.It Cm slmrmcthr Ns Ar %02d
Client
.Tn RPC
request service thread
.It Cm slmrmithr Ns Ar %02d
.Tn I/O
node
.Tn RPC
request service thread
.It Cm slmrmmthr Ns Ar %02d
.No Inter- Ns Tn MDS RPC
request service thread
.It Cm slmtiosthr
Timed
.Tn I/O
stats updater thread
.It Cm slmupschedthr- Ns Ar %s
Per-site update scheduler thread
.It Cm slmusklndplthr Ns Ar %d
.Tn LNET
userland socket poll thread
.It Cm everyone
All threads (default, where applicable)
.El
.Sh FILES
.Bl -tag -width Pa
.It Xo
.Pa /var/run/slashd. Ns Ic %h Ns Pa .sock
.Xc
default
.Xr slashd 8
control socket
.El
.Sh SEE ALSO
.Xr pflctl 7 ,
.Xr sladm 7 ,
.Xr slashd 8 ,
.Xr slictl 8
