#!/usr/bin/perl -W
# $Id$

use Cwd;
use warnings;
use strict;

$ENV{PSC_TIMEOUT} = 1;

sub cpnwalk {
	my ($fn, $f) = @_;
	my @cpn = split m[/];
	for (my $i = 1; $i < @cpn; $i++) {
		$f->(join "/", @cpn[0 .. $i]);
	}
}

while (<>) {
	# example pathname: /usr/users/2/username/file/path/etc
	cpnwalk $_, sub {
		my $fn = Cwd::realpath(shift);
		my $s2fn = $fn;
		if ($s2fn =~ s!^/usr/(u[eo])/!!) {
			system "slictl-$1 import -v \Q$fn\E \Q$s2fn\E";
		} else {
			warn "skipping import of file outside archiver root: $fn\n";
		}
	};
}
