.\" $Id$
.\" %PSCGPL_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2010, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd July 29, 2010
.Dt SLKEYMGT 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm slkeymgt
.Nd manage shared keys for
.Tn SLASH
services
.Sh SYNOPSIS
.Nm slkeymgt
.Op Fl c
.Op Fl D Ar datadir
.Sh DESCRIPTION
The
.Nm
utility provides management capabilities for the administration of the
shared keys used for communication among various
.Tn SLASH
services.
The default behavior checks the integrity of an installed key.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl D Ar datadir
Specify an alternative directory where operation data is stored.
Defaults to
.Pa /var/lib/slash .
.It Fl c
Create a new key.
This operation is carried out automatically by
.Tn MDS
servers on startup if no key is installed.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /var/lib/slash/authbuf.key
shared key
.El
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8 ,
.Xr sliod 8
