.\" $Id$
.\" %PSCGPL_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2009-2012, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd August 14, 2012
.Dt SLMKFS 8
.ds volume PSC \- SLASH Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm slmkfs
.Nd format a
.Tn SLASH
backing store file system
.Sh SYNOPSIS
.Nm slmkfs
.Op Fl iW
.Op Fl c Ar conf
.Op Fl D Ar datadir
.Op Fl I Ar siteid
.Op Fl u Ar fsuuid
.Pa fsroot
.Sh DESCRIPTION
The
.Nm
utility initializes the internal file directory structure necessary for
use with
.Tn SLASH
metadata server and
.Tn I/O
node operation for the specified
file system root
.Ar fsroot .
.Pp
The directory structures includes facilities such as the immutable
namespace,
which is responsible for providing persistent access to file data
regardless of file pathname renames and unlinks, and the replication
queue.
.Pp
The following options are available:
.Bl -tag -offset 3n -width 3n
.It Fl c Ar conf
Specify configuration file from which to extract other parameters
.Pq such as Fl u .
.It Fl D Ar datadir
Specify an alternative directory where operation data is stored.
Defaults to
.Pa /var/lib/slash .
.It Fl I Ar siteid
Specify this site's ID number.
Should match the same value of the site ID from its profile in the
specified configuration file.
.It Fl i
Format a file system suitable for use with
.Tn I/O
nodes.
The default is to format the file system for use with an
.Tn MDS
server.
.It Fl u
Specify file system
.Tn UUID
.Po for
.Tn I/O nodes only
.Pc .
.It Fl W
Completely wipe all existing data on the destination file system before
initializing the internal structure.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Ar fsroot Ns Pa /.slmd/bmap.odtab
block map assignments
.It Ar fsroot Ns Pa /.slmd/cursor
journal cursor
.It Ar fsroot Ns Pa /.slmd/fidns
immutable namespace
.It Ar fsroot Ns Pa /.slmd/fsuuid
file system universally unique ID
.It Ar fsroot Ns Pa /.slmd/op- Ns Ar *
various operation logs
.It Ar fsroot Ns Pa /.slmd/ptrunc.odt
partial truncation resolutions
.It Ar fsroot Ns Pa /.slmd/repl.odt
replication queue
.It Ar fsroot Ns Pa /.slmd/repls
replication queue
.It Ar fsroot Ns Pa /.slmd/timestamp
file system creation date
.It Ar fsroot Ns Pa /.slmd/tmp
temporary processing directory
.El
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8
