.\" $Id$
.\" %GPL_START_LICENSE%
.\" ---------------------------------------------------------------------
.\" Copyright 2015, Google, Inc.
.\" Copyright (c) 2009-2015, Pittsburgh Supercomputing Center (PSC).
.\" All rights reserved.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or (at
.\" your option) any later version.
.\"
.\" This program is distributed WITHOUT ANY WARRANTY; without even the
.\" implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
.\" PURPOSE.  See the GNU General Public License contained in the file
.\" `COPYING-GPL' at the top of this distribution or at
.\" https://www.gnu.org/licenses/gpl-2.0.html for more details.
.\" ---------------------------------------------------------------------
.\" %END_LICENSE%
.Dd November 6, 2015
.Dt SLMKFS 8
.ds volume PSC \- SLASH2 Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm slmkfs
.Nd format a
.Tn SLASH2
backing store file system
.Sh SYNOPSIS
.Nm slmkfs
.Op Fl iW
.Op Fl I Ar siteid:resid
.Op Fl u Ar fsuuid
.Pa fsroot
.Sh DESCRIPTION
The
.Nm
utility initializes the internal file directory structure necessary for
use with
.Tn SLASH2
metadata server and
.Tn I/O
node operation for the specified
file system root
.Ar fsroot .
.Pp
The directory structures includes facilities such as the immutable
namespace,
which is responsible for providing persistent access to file data
regardless of file pathname renames and unlinks, and the replication
queue.
.Pp
The following options are available:
.Bl -tag -offset 3n -width 3n
.It Fl I Ar siteid:resid
Specify this resource's ID number.
The format is the site ID, in hexadecimal notation with the
.Sq 0x
prefix, followed by a colon
.Pq Sq :\& ,
followed by the resource ID, in hexadecimal notation with the
.Sq 0x
prefix.
Both IDs must match the corresponding profile from the
.Xr slcfg 5
configuration file for this resource.
.It Fl i
Format a file system suitable for use with
.Tn I/O
nodes.
The default is to format the file system for use with an
.Tn MDS
server.
.It Fl u
Specify the file system
.Tn UUID
.Po for
.Tn I/O nodes only
.Pc .
Must be in hexadecimal format with the
.Sq 0x
prefix.
.It Fl W
Completely wipe all existing data on the destination file system before
initializing the internal structure.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Ar fsroot Ns Pa /.slmd/bmap.odtab
block map assignments
.It Ar fsroot Ns Pa /.slmd/cursor
journal cursor
.It Ar fsroot Ns Pa /.slmd/fidns/
immutable namespace
.It Ar fsroot Ns Pa /.slmd/fsuuid
file system universally unique ID
.It Ar fsroot Ns Pa /.slmd/op- Ns Ar *
various operation logs
.It Ar fsroot Ns Pa /.slmd/ptrunc.odt
partial truncation resolutions
.It Ar fsroot Ns Pa /.slmd/resid
resource identifier
.It Ar fsroot Ns Pa /.slmd/timestamp
file system creation date
.It Ar fsroot Ns Pa /.slmd/tmp
temporary processing directory
.El
.Sh SEE ALSO
.Xr sladm 7 ,
.Xr slashd 8
