# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		dumpfid
SRCS+=		dumpfid.c
SRCS+=		${PFL_BASE}/psc_util/crc.c
SRCS+=		${PFL_BASE}/psc_util/log.c

MODULES+=	lnet-hdrs pfl

include ${SLASHMK}
